micronaut:
  application:
    name: aluguelcarros
  server:
    cors:
      enabled: true

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/aluguel_carros`}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages:
        - com.aluguelcarros.model
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
